<?php

namespace sprintBundle\Repository;

/**
 * sprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sprintRepository extends \Doctrine\ORM\EntityRepository
{
}
