<?php

namespace EventBundle\Repository;

/**
 * CertifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertifRepository extends \Doctrine\ORM\EntityRepository
{
}
