<?php

namespace EventBundle\Repository;

/**
 * EventsAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
