<?php

namespace EventBundle\Repository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findType($input)
    {
        $query=$this->getEntityManager()->createQuery("SELECT f FROM EventBundle:Participant f 
WHERE f.choix='$input'");
        return $query->getResult();
    }
}
