<?php

namespace EventBundle\Repository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findType($input)
    {
        $query=$this->getEntityManager()->createQuery("SELECT f FROM EventBundle:Participant f 
        WHERE f.choix='$input'");
        return $query->getResult();
    }


    public function findNomp($input)
    {
        $query=$this->getEntityManager()->createQuery("SELECT f FROM EventBundle:Participant f 
        WHERE f.nomp LIKE '%$input%' 
        or f.prenomp LIKE '%$input%' 
        or f.email LIKE '%$input%'");

        return $query->getResult();
    }

    /*public function findchoix()
    {
        $query=$this->getEntityManager()->createQuery("SELECT f.choix FROM EventBundle:Participant f ");
        return $query->getResult();
    }*/


    public function tri()
    {
        $query=$this->getEntityManager()->createQuery("SELECT * from EventBundle:EventsAdmin ORDER BY nomp ASC");
        return $query->getResult();
    }


}
