api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_backlog_index:
    path:     /ProjectBacklog/index
    defaults: { _controller: BacklogBundle:Default:IndexProjectBacklogApi }

api_view_ProjectBacklog_tasks:
    path:     /ProjectBacklog/view/{id}
    defaults: { _controller: BacklogBundle:Default:view_ProjectBacklogApi }

api_view_BacklogTask:
    path:     /ProjectBacklog/view/{id_b}/task/view/{id}
    defaults: { _controller: BacklogBundle:Default:ViewBacklogTaskApi }

#  ****************************** Ghassen's Work *******************************************************
IndexEventApi:
    path:     /Event/Index/{idev}
    defaults: { _controller: EventBundle:EventAdmin:IndexEventApi }

AddEventApi:
    path:     /Event/Add/{idev}/{titre}/{type}/{cap}/{dateEvent}/{dateEnd}/{img}
    defaults: { _controller: EventBundle:EventAdmin:AddEventApi }

IndexPartApi:
    path:     /Participant/Index
    defaults: { _controller: EventBundle:Participant:IndexPartApi }

DeleteEventApi:
    path:     /Event/Delete/{idev}
    defaults: { _controller: EventBundle:EventAdmin:DeleteEventApi }

StatApi:
    path:     /Event/Stat
    defaults: { _controller: EventBundle:EventAdmin:Statistique }

UpdateEventApi:
    path:     /Event/Update/{idev}/{TitreEvent}/{NumeroEvent}/{TypeEvent}/{DateEvent}/{enddateEvent}/{image_name}
    defaults: { _controller: EventBundle:EventAdmin:UpdateEventApi }

#  ****************************** End Work *******************************************************