api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_backlog_index:
    path:     /ProjectBacklog/index
    defaults: { _controller: BacklogBundle:Default:IndexProjectBacklogApi }

api_view_ProjectBacklog_tasks:
    path:     /ProjectBacklog/view/{id}
    defaults: { _controller: BacklogBundle:Default:view_ProjectBacklogApi }

api_view_BacklogTask:
    path:     /ProjectBacklog/view/{id_b}/task/view/{id}
    defaults: { _controller: BacklogBundle:Default:ViewBacklogTaskApi }

api_delete_BacklogTask:
    path:     /ProjectBacklog/view/{id_b}/task/remove/{id}
    defaults: { _controller: BacklogBundle:Default:RemoveBacklogTaskApi }

api_add_BacklogTask:
    path:     /ProjectBacklog/view/{id_b}/task/add/{title}/{story_points}/{state}/{priority}/{desc_f}/{sprint_id}/{finished_date}
    defaults: { _controller: BacklogBundle:Default:AddBacklogTaskApi }

SCARRAA_LOGIN:
    path:     /User/login
    defaults: { _controller: EntrepriseBundle:Entreprise:loginScarra }

SCARRAA_Entreprise_afficher:
    path:     /Entreprise/afficher
    defaults: { _controller: EntrepriseBundle:Entreprise:apiAfficher }

SCARRAA_Entreprise_delete:
    path:     /Entreprise/delete/{id}
    defaults: { _controller: EntrepriseBundle:Entreprise:apiDelete }

SCARRAA_Entreprise_ajouter:
    path:     /Entreprise/ajouter
    defaults: { _controller: EntrepriseBundle:Entreprise:apiAjouter }

SCARRAA_Entreprise_modifier:
    path:     /Entreprise/update/{id}
    defaults: { _controller: EntrepriseBundle:Entreprise:apiModifier }

SCARRAA_User_read:
    path:     /User/afficher
    defaults: { _controller: EntrepriseBundle:Entreprise:apiUserRead }

SCARRAA_User_Delete:
    path:     /User/delete/{id}
    defaults: { _controller: EntrepriseBundle:Entreprise:apiUserDelete }

SCARRAA_User_Create:
    path:     /User/ajouter
    defaults: { _controller: EntrepriseBundle:Entreprise:apiUserCreate }

SCARRAA_User_Update:
    path:     /User/update/{id}
    defaults: { _controller: EntrepriseBundle:Entreprise:apiUserUpdate }


