api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_backlog_index:
    path:     /ProjectBacklog/index
    defaults: { _controller: BacklogBundle:Default:IndexProjectBacklogApi }

api_view_ProjectBacklog_tasks:
    path:     /ProjectBacklog/view/{id}
    defaults: { _controller: BacklogBundle:Default:view_ProjectBacklogApi }

api_view_BacklogTask:
    path:     /ProjectBacklog/view/{id_b}/task/view/{id}
    defaults: { _controller: BacklogBundle:Default:ViewBacklogTaskApi }

api_delete_BacklogTask:
    path:     /ProjectBacklog/view/{id_b}/task/remove/{id}
    defaults: { _controller: BacklogBundle:Default:RemoveBacklogTaskApi }

api_add_BacklogTask:
    path:     /ProjectBacklog/view/{id_b}/task/add/{title}/{story_points}/{state}/{priority}/{desc_f}/{sprint_id}/{finished_date}
    defaults: { _controller: BacklogBundle:Default:AddBacklogTaskApi }

api_add_Backlog:
    path:     /ProjectBacklog/new/{project_id}
    defaults: { _controller: BacklogBundle:Default:AddBacklogApi }

api_stat_in_progress_backlog:
    path:     /ProjectBacklog/stat/inprogress/backlog/{id}/user/{user_id}
    defaults: { _controller: BacklogBundle:Default:BacklogStatInProgressApi }

api_stat_to_do_backlog:
    path:     /ProjectBacklog/stat/todo/backlog/{id}/user/{user_id}
    defaults: { _controller: BacklogBundle:Default:BacklogStatToDoApi }

api_stat_done_backlog:
    path:     /ProjectBacklog/stat/done/backlog/{id}/user/{user_id}
    defaults: { _controller: BacklogBundle:Default:BacklogStatDoneApi }

IndexEventApi:
    path:     /Event/Index/{idev}
    defaults: { _controller: EventBundle:EventAdmin:IndexEventApi }

AddEventApi:
    path:     /Event/Add/{idev}/{titre}/{type}/{cap}/{dateEvent}/{dateEnd}/{img}
    defaults: { _controller: EventBundle:EventAdmin:AddEventApi }

IndexPartApi:
    path:     /Participant/Index
    defaults: { _controller: EventBundle:Participant:IndexPartApi }

DeleteEventApi:
    path:     /Event/Delete/{idev}
    defaults: { _controller: EventBundle:EventAdmin:DeleteEventApi }

StatApi:
    path:     /Event/Stat
    defaults: { _controller: EventBundle:EventAdmin:Statistique }

UpdateEventApi:
    path:     /Event/Update/{idev}/{TitreEvent}/{NumeroEvent}/{TypeEvent}/{DateEvent}/{enddateEvent}/{image_name}
    defaults: { _controller: EventBundle:EventAdmin:UpdateEventApi }

#  ****************************** End Work *******************************************************
#  ****************************** Begin ahmedbs *******************************************************
#  **************** Project
api_afficher_Project:
    path:     /Project/afficher
    defaults: { _controller: projetsBundle:projets:afficherProjectApi  }

api_ajouter_Project:
    path:     /Project/ajouter/
    defaults: { _controller: projetsBundle:projets:createProjectApi  }

api_More_Project:
    path:     /Project/More/{id}
    defaults: { _controller: projetsBundle:projets:MoreProjectApi  }

api_delete_Project:
    path:     /Project/delete/{id}
    defaults: { _controller: projetsBundle:projets:api_deleteProject  }
api_update_Project:
    path:     /Project/update/{id}
    defaults: { _controller: projetsBundle:projets:updateprojetApi  }

api_archiver_Project:
    path:     /Project/archiver/{id}
    defaults: { _controller: projetsBundle:projets:api_archiverProject  }
api_NOTarchiver_Project:
    path:     /Project/NOTarchiver/{id}
    defaults: { _controller: projetsBundle:projets:api_NOTarchiverProject  }
api_affiche_archiver_Project:
    path:     /Project/affiche_archiver
    defaults: { _controller: projetsBundle:projets:Aff_archiverProjectApi  }

api_Progress_Project:
    path:     /Project/Progress/{id}
    defaults: { _controller: projetsBundle:projets:ProgressProjectApi  }
api_Completed_Project:
    path:     /Project/Completed/{id}
    defaults: { _controller: projetsBundle:projets:CompletedProjectApi  }

#  **************** sprint
api_afficher_sprint:
    path:     /sprint/afficher/{id}
    defaults: { _controller: sprintBundle:sprint:afficherSprintApi  }
api_ajouter_sprint:
    path:     /sprint/ajouter/
    defaults: { _controller: sprintBundle:sprint:createSprintApi  }
api_delete_sprint:
    path:     /sprint/delete/{id}
    defaults: { _controller: sprintBundle:sprint:api_deleteSprint  }
api_update_sprint:
    path:     /sprint/update/{id}
    defaults: { _controller: sprintBundle:sprint:updateSprintApi  }
#not drag an drop
api_DRAG_DROP_sprint:
    path:     /sprint/DRAG_DROP/{id}
    defaults: { _controller: sprintBundle:sprint:afficherSprint_taskApi  }
api_update_DRAG_DROP_sprint:
    path:     /sprint/update_DRAG_DROP/{id}/{idd}/{etat}
    defaults: { _controller: sprintBundle:sprint:update_drag_drop_Api  }

#  ****************************** END ahmedbs *******************************************************