<?php

namespace BacklogBundle\Repository;

/**
 * BacklogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacklogRepository extends \Doctrine\ORM\EntityRepository
{
}
