<?php

namespace BacklogBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

    public function CommentairesTask($id){
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM BacklogBundle:Commentaire c WHERE c.task ='$id' ");
        return $query->getResult();
    }
}
