<?php

namespace BacklogBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

    public function backlogTasks($id){
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM BacklogBundle:Task c WHERE c.backlog ='$id' AND c.archive = 0  ");
        return $query->getResult();
    }

    public function backlogArchives($id){
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM BacklogBundle:Task c WHERE c.backlog ='$id' AND c.archive = 1 ");
        return $query->getResult();
    }
}
