sprint_homepage:
    path:     /
    defaults: { _controller: sprintBundle:Default:index }

createsprint:
    path:     /createsprint/{id_projet}
    defaults: { _controller: sprintBundle:sprint:createsprint }

affichersprint:
    path:     /affichersprint/{id_projet}
    defaults: { _controller: sprintBundle:sprint:affichersprint }

updatesprint:
    path:     /updatesprint/{idU}/{id}
    defaults: { _controller: sprintBundle:sprint:updatesprint }

deletesprint:
    path:     /deletesprint/{id}
    defaults: { _controller: sprintBundle:sprint:deletesprint }
DRAG_DROP:
    path:     /DRAG_DROP/{idd}
    defaults: { _controller: sprintBundle:sprint:DRAG_DROP }
stat_sprint:
    path:     /stat_sprint/{idS}
    defaults: { _controller: sprintBundle:sprint:statsprint }
