<?php

namespace MeetingBundle\Repository;

/**
 * MeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingRepository extends \Doctrine\ORM\EntityRepository
{
    public function tri()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM MeetingBundle:Meeting c ORDER BY c.nbrmeeting DESC  ");
        return $query->getResult();

    }

}
