user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
register:
    path:     /Register
    defaults: { _controller: UserBundle:Default:register }
home:
    path:     /home
    defaults: { _controller: UserBundle:Security:redirect }
