subscription_homepage:
    path:     /
    defaults: { _controller: SubscriptionBundle:Default:index }

readtarif:
    path:     /readtarif
    defaults: { _controller: SubscriptionBundle:Tarif:readtarif }

createtarif:
    path:     /createtarif
    defaults: { _controller: SubscriptionBundle:Tarif:createtarif }

deletetarif:
    path:     /deletetarif/{id}
    defaults: { _controller: SubscriptionBundle:Tarif:deletetarif }

updatetarif:
    path:     /updatetarif/{id}
    defaults: { _controller: SubscriptionBundle:Tarif:updatetarif }

readsub:
    path:     /readsub
    defaults: { _controller: SubscriptionBundle:Subscription:readsub }

createsub:
    path:     /createsub
    defaults: { _controller: SubscriptionBundle:Subscription:createsub }

deletesub:
    path:     /deletesub/{id}
    defaults: { _controller: SubscriptionBundle:Subscription:deletesub }

updatesub:
    path:     /upadatesub/{id}
    defaults: { _controller: SubscriptionBundle:Subscription:upadatesub }
