<?php

namespace projetsBundle\Repository;

/**
 * projetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projetsRepository extends \Doctrine\ORM\EntityRepository
{
}
