event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Default:index }

_addevent:
    path:     /Addevent
    defaults: { _controller: EventBundle:Event:Addevent }

_updatevent:
    path:     /Updatevent/{nomp}
    defaults: { _controller: EventBundle:Event:Updatevent }

_readevent:
    path:     /Readevent
    defaults: { _controller: EventBundle:Event:Readevent }

_deletevent:
    path:     /Deletevent/{nomp}
    defaults: { _controller: EventBundle:Event:Deletevent }

_searchevent:
    path:     /Searchevent
    defaults: { _controller: EventBundle:Event:Searchevent }




addevent:
    path:     /addeventA
    defaults: { _controller: EventBundle:EventAdmin:addevent }

afficherevent:
    path:     /afficherevent
    defaults: { _controller: EventBundle:EventAdmin:afficherevent }

update_events:
    path:     /updateEvents/{idev}
    defaults: { _controller: EventBundle:EventAdmin:updateEvents }

deleteevents:
    path:     /deleteevents/{idev}
    defaults: { _controller: EventBundle:EventAdmin:deleteevents }

searchevents:
    path:     /searchevents
    defaults: { _controller: EventBundle:EventAdmin:searchevents }
